name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/enterprise-devops-platform/app/transaction-service

            sudo docker stop transaction-service || true
            sudo docker rm transaction-service || true

            sudo docker build -t transaction-service .

            sudo docker run -d \
              --name transaction-service \
              -p 5001:5000 \
              transaction-service
